#! /bin/sh



pgrep -x sxhkd > /dev/null || sxhkd &

pkill polybar

polybar top &
polybar bottom &
stretchly &



if [ -z "$(xrandr -q | grep -w connected | grep HDMI1)" ]
then
  if [ $(xrandr -q | grep -w connected | grep DP1 | wc -l) -eq 2 ]
  then
    bspc monitor eDP1 -d I II III IV V
    bspc monitor DP1 -d VI VII VIII IX X

    polybar top3 &
    polybar bottom3 &

    bspc config bottom_padding 20

  else
    bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
  fi
else
  bspc monitor eDP1 -d I II III IV V
  bspc monitor HDMI1 -d VI VII VIII IX X

  polybar top2 &
  polybar bottom2 &

  bspc config bottom_padding 20
fi

bspc config border_width         0
bspc config window_gap          16
bspc config border_radius       16

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
